In [4]:
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression

In [5]:
from sklearn.metrics import roc_auc_score

In [6]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, f1_score

In [7]:
import polars as pl

In [8]:
df = pl.read_csv('/kaggle/input/titanic-dataset/Titanic-Dataset.csv')
df

shape: (891, 12)
┌─────────────┬──────────┬────────┬──────────────────┬───┬────────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name             ┆ … ┆ Ticket     ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---              ┆   ┆ ---        ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str              ┆   ┆ str        ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪══════════════════╪═══╪════════════╪═════════╪═══════╪══════════╡
│ 1           ┆ 0        ┆ 3      ┆ Braund, Mr. Owen ┆ … ┆ A/5 21171  ┆ 7.25    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Harris           ┆   ┆            ┆         ┆       ┆          │
│ 2           ┆ 1        ┆ 1      ┆ Cumings, Mrs.    ┆ … ┆ PC 17599   ┆ 71.2833 ┆ C85   ┆ C        │
│             ┆          ┆        ┆ John Bradley     ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ (Fl…             ┆   ┆            ┆         ┆       ┆          │
│ 3           ┆ 1        ┆ 3      ┆ Heikkinen, Miss. ┆ … ┆ STON/O2.   ┆ 7.925   ┆ null  ┆ S        │
│             ┆          ┆        ┆ Laina            ┆   ┆ 3101282    ┆         ┆       ┆          │
│ 4           ┆ 1        ┆ 1      ┆ Futrelle, Mrs.   ┆ … ┆ 113803     ┆ 53.1    ┆ C123  ┆ S        │
│             ┆          ┆        ┆ Jacques Heath (… ┆   ┆            ┆         ┆       ┆          │
│ 5           ┆ 0        ┆ 3      ┆ Allen, Mr.       ┆ … ┆ 373450     ┆ 8.05    ┆ null  ┆ S        │
│             ┆          ┆        ┆ William Henry    ┆   ┆            ┆         ┆       ┆          │
│ …           ┆ …        ┆ …      ┆ …                ┆ … ┆ …          ┆ …       ┆ …     ┆ …        │
│ 887         ┆ 0        ┆ 2      ┆ Montvila, Rev.   ┆ … ┆ 211536     ┆ 13.0    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Juozas           ┆   ┆            ┆         ┆       ┆          │
│ 888         ┆ 1        ┆ 1      ┆ Graham, Miss.    ┆ … ┆ 112053     ┆ 30.0    ┆ B42   ┆ S        │
│             ┆          ┆        ┆ Margaret Edith   ┆   ┆            ┆         ┆       ┆          │
│ 889         ┆ 0        ┆ 3      ┆ Johnston, Miss.  ┆ … ┆ W./C. 6607 ┆ 23.45   ┆ null  ┆ S        │
│             ┆          ┆        ┆ Catherine Hele…  ┆   ┆            ┆         ┆       ┆          │
│ 890         ┆ 1        ┆ 1      ┆ Behr, Mr. Karl   ┆ … ┆ 111369     ┆ 30.0    ┆ C148  ┆ C        │
│             ┆          ┆        ┆ Howell           ┆   ┆            ┆         ┆       ┆          │
│ 891         ┆ 0        ┆ 3      ┆ Dooley, Mr.      ┆ … ┆ 370376     ┆ 7.75    ┆ null  ┆ Q        │
│             ┆          ┆        ┆ Patrick          ┆   ┆            ┆         ┆       ┆          │
└─────────────┴──────────┴────────┴──────────────────┴───┴────────────┴─────────┴───────┴──────────┘

In [9]:
new_df = df.clone()
new_df = new_df.drop(['Name'])

In [10]:
new_df = new_df.drop(['Ticket', 'Cabin'])
new_df

shape: (891, 9)
┌─────────────┬──────────┬────────┬────────┬───┬───────┬───────┬─────────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Sex    ┆ … ┆ SibSp ┆ Parch ┆ Fare    ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---    ┆   ┆ ---   ┆ ---   ┆ ---     ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str    ┆   ┆ i64   ┆ i64   ┆ f64     ┆ str      │
╞═════════════╪══════════╪════════╪════════╪═══╪═══════╪═══════╪═════════╪══════════╡
│ 1           ┆ 0        ┆ 3      ┆ male   ┆ … ┆ 1     ┆ 0     ┆ 7.25    ┆ S        │
│ 2           ┆ 1        ┆ 1      ┆ female ┆ … ┆ 1     ┆ 0     ┆ 71.2833 ┆ C        │
│ 3           ┆ 1        ┆ 3      ┆ female ┆ … ┆ 0     ┆ 0     ┆ 7.925   ┆ S        │
│ 4           ┆ 1        ┆ 1      ┆ female ┆ … ┆ 1     ┆ 0     ┆ 53.1    ┆ S        │
│ 5           ┆ 0        ┆ 3      ┆ male   ┆ … ┆ 0     ┆ 0     ┆ 8.05    ┆ S        │
│ …           ┆ …        ┆ …      ┆ …      ┆ … ┆ …     ┆ …     ┆ …       ┆ …        │
│ 887         ┆ 0        ┆ 2      ┆ male   ┆ … ┆ 0     ┆ 0     ┆ 13.0    ┆ S        │
│ 888         ┆ 1        ┆ 1      ┆ female ┆ … ┆ 0     ┆ 0     ┆ 30.0    ┆ S        │
│ 889         ┆ 0        ┆ 3      ┆ female ┆ … ┆ 1     ┆ 2     ┆ 23.45   ┆ S        │
│ 890         ┆ 1        ┆ 1      ┆ male   ┆ … ┆ 0     ┆ 0     ┆ 30.0    ┆ C        │
│ 891         ┆ 0        ┆ 3      ┆ male   ┆ … ┆ 0     ┆ 0     ┆ 7.75    ┆ Q        │
└─────────────┴──────────┴────────┴────────┴───┴───────┴───────┴─────────┴──────────┘

In [11]:
new_df = new_df.to_dummies("Sex")

In [12]:
new_df = new_df.to_dummies("Embarked")

In [13]:
X = new_df.drop(['Survived'])
X

shape: (891, 12)
┌────────────┬────────┬────────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ PassengerI ┆ Pclass ┆ Sex_female ┆ Sex_male ┆ … ┆ Embarked_C ┆ Embarked_ ┆ Embarked_ ┆ Embarked_ │
│ d          ┆ ---    ┆ ---        ┆ ---      ┆   ┆ ---        ┆ Q         ┆ S         ┆ null      │
│ ---        ┆ i64    ┆ u8         ┆ u8       ┆   ┆ u8         ┆ ---       ┆ ---       ┆ ---       │
│ i64        ┆        ┆            ┆          ┆   ┆            ┆ u8        ┆ u8        ┆ u8        │
╞════════════╪════════╪════════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1          ┆ 3      ┆ 0          ┆ 1        ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ 2          ┆ 1      ┆ 1          ┆ 0        ┆ … ┆ 1          ┆ 0         ┆ 0         ┆ 0         │
│ 3          ┆ 3      ┆ 1          ┆ 0        ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ 4          ┆ 1      ┆ 1          ┆ 0        ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ 5          ┆ 3      ┆ 0          ┆ 1        ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ …          ┆ …      ┆ …          ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 887        ┆ 2      ┆ 0          ┆ 1        ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ 888        ┆ 1      ┆ 1          ┆ 0        ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ 889        ┆ 3      ┆ 1          ┆ 0        ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ 890        ┆ 1      ┆ 0          ┆ 1        ┆ … ┆ 1          ┆ 0         ┆ 0         ┆ 0         │
│ 891        ┆ 3      ┆ 0          ┆ 1        ┆ … ┆ 0          ┆ 1         ┆ 0         ┆ 0         │
└────────────┴────────┴────────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [14]:
y = new_df['Survived']
y

shape: (891,)
Series: 'Survived' [i64]
[
	0
	1
	1
	1
	0
	…
	0
	1
	0
	1
	0
]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, stratify=y)
X_train

shape: (668, 12)
┌────────────┬────────┬────────────┬──────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ PassengerI ┆ Pclass ┆ Sex_female ┆ Sex_male ┆ … ┆ Embarked_C ┆ Embarked_ ┆ Embarked_ ┆ Embarked_ │
│ d          ┆ ---    ┆ ---        ┆ ---      ┆   ┆ ---        ┆ Q         ┆ S         ┆ null      │
│ ---        ┆ i64    ┆ u8         ┆ u8       ┆   ┆ u8         ┆ ---       ┆ ---       ┆ ---       │
│ i64        ┆        ┆            ┆          ┆   ┆            ┆ u8        ┆ u8        ┆ u8        │
╞════════════╪════════╪════════════╪══════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 487        ┆ 1      ┆ 1          ┆ 0        ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ 239        ┆ 2      ┆ 0          ┆ 1        ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ 723        ┆ 2      ┆ 0          ┆ 1        ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ 185        ┆ 3      ┆ 1          ┆ 0        ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ 57         ┆ 2      ┆ 1          ┆ 0        ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ …          ┆ …      ┆ …          ┆ …        ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 548        ┆ 2      ┆ 0          ┆ 1        ┆ … ┆ 1          ┆ 0         ┆ 0         ┆ 0         │
│ 470        ┆ 3      ┆ 1          ┆ 0        ┆ … ┆ 1          ┆ 0         ┆ 0         ┆ 0         │
│ 737        ┆ 3      ┆ 1          ┆ 0        ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ 463        ┆ 1      ┆ 0          ┆ 1        ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
│ 822        ┆ 3      ┆ 0          ┆ 1        ┆ … ┆ 0          ┆ 0         ┆ 1         ┆ 0         │
└────────────┴────────┴────────────┴──────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [16]:
model = XGBClassifier()

In [17]:
# log_reg = LogisticRegression()
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [18]:
y_pred_xgboost = model.predict(X_test)
accuracy_score(y_test, y_pred_xgboost)

0.7713004484304933

In [19]:
f1_score(y_test, y_pred_xgboost)

0.6832298136645963

Был произведен сравнительный анализ между f1_score и accuracy_score. Так как у нас задача с классификацией в виде предсказания класса, поэтому рассматривались такие метрики. Accuracy_score показал более лучшую точность предсказания, чем f1_score